# WordPress Service - Internal endpoint for the ingress to route traffic
# Uses ClusterIP since ingress handles external access
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: ClusterIP           # Internal service - ingress provides external access
  ports:
    - port: 80              # Service listens on port 80
      targetPort: 80        # Routes to container port 80
  selector:
    app: wordpress
    tier: frontend          # Routes traffic to WordPress frontend pods
