# MySQL Secret - Stores the database password securely
# Note: In production, use more secure methods like external secret management
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: wordpress
stringData:
  password: wordpress  # Change this to a strong password in production
