# WordPress Service - Internal endpoint for the ingress to route traffic
# Uses ClusterIP since ingress handles external access
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: ClusterIP           # Internal service - ingress provides external access
  ports:
    - port: 80              # Service listens on port 80
      targetPort: 80        # Routes to container port 80
  selector:
    app: wordpress
    tier: frontend          # Routes traffic to WordPress frontend pods
---
# WordPress Deployment - Manages WordPress application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate          # Ensures clean restarts (important for stateful apps)
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        # Database connection settings
        - name: WORDPRESS_DB_HOST
          value: mysql      # References the MySQL service name
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password # Uses the same password as MySQL
        ports:
        - containerPort: 80
          name: wordpress
        # Resource limits to prevent WordPress from consuming too many resources
        resources:
          requests:
            memory: "256Mi"  # Minimum memory guaranteed
            cpu: "250m"      # Minimum CPU guaranteed (0.25 cores)
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "500m"      # Maximum CPU allowed (0.5 cores)
        # Mount storage for WordPress files and uploads
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html  # WordPress web root directory
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}        # Temporary storage - use PVC for production
