# MySQL Deployment - Manages MySQL database pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  replicas: {{ .Values.replicaCount.mysql }}
  strategy:
    type: Recreate  # Ensures only one MySQL instance runs at a time
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
        # Database root password from the secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-mysql-pass
              key: password
        # Automatically creates a database named 'wordpress'
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database.name }}
        ports:
        - containerPort: 3306
          name: mysql
        {{- if .Values.mysql.resources }}
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.mysql.persistence.enabled }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        {{- end }}
      {{- if .Values.mysql.persistence.enabled }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress.fullname" . }}-mysql-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
