apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-namespace
  labels:              # <- also corrected 'label' to 'labels'
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - name: vproapp-port
          containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
