---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Python3 PyMySQL package (required for mysql_db module)
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Set root password in MariaDB (MariaDB syntax)
      ansible.builtin.shell: |
        mysql -u root <<EOF
        SET PASSWORD FOR 'root'@'localhost' = PASSWORD('rootpassword');
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash


    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_user: root
        login_password: rootpassword

