Vagrant.configure("2") do |config|
  # Hostmanager plugin setup
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Common VM config
  vm_ram = 4096
  vm_cpus = 2
  base_box = "ubuntu/jammy64"

  machines = {
    "jenkins" => { ip: "192.168.56.10", ports: { 8080 => 8080 }, script: "install-jenkins.sh" },
    "nexus"   => { ip: "192.168.56.11", ports: { 8081 => 8081 }, script: "install-nexus.sh" },
    "sonar"   => { ip: "192.168.56.12", ports: { 9000 => 9000 }, script: "install-sonarqube.sh" }
  }

  machines.each do |name, config_data|
    config.vm.define name do |vm|
      vm.vm.box = base_box
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: config_data[:ip]

      config_data[:ports].each do |guest, host|
        vm.vm.network "forwarded_port", guest: guest, host: host, auto_correct: true
      end

      vm.vm.provider "virtualbox" do |vb|
        vb.memory = vm_ram
        vb.cpus = vm_cpus
      end

      vm.vm.provision "shell", path: config_data[:script]
    end
  end
end
