Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "ubuntu/jammy64"
    scriptbox.vm.hostname = "scriptbox"
    scriptbox.vm.network "private_network", ip: "pin"
    scriptbox.vm.private_network "private_network", ip: "192.168.56.37"
    scriptbox.vm.synced_folder "./shared", "/home/vagrant/shared"
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "eurolinux-vagrant/centos-stream-9"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.37"
    web01.vm.synced_folder "./shared", "/home/vagrant/shared"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end


end
