apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80          # ClusterIP port
      # name: tomcat-port
      targetPort: 8080  # Container port
      nodePort: 30000   # Optional: must be between 30000–32767
