apiVersion: v1
kind: Pod
metadata:
  name: tomcat-server
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat
      image: tomcat:9.0
      ports:
        - name: tomcat-port
          containerPort: 8080
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
